---
loader: taskgraph.loader.transform:loader

transforms:
  - src.transforms:taskcluster_images
  - src.transforms:add_task_env
  - taskgraph.transforms.job:transforms
  - taskgraph.transforms.task:transforms

job-defaults:
  worker-type: ci
  run:
    using: bare
  worker:
    max-run-time: 600
    # for the moment, let's use rust:latest; we can either build a custom image
    # or include the rust version here later (TODO)
    docker-image: 'rust:latest'

jobs:
  rust-client:
    description: test rust client
    run:
      install: cd clients/client-rust
      command: cargo test && cargo build --production
